# Generated by Django 4.0.4 on 2022-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.JSONField(default=list)),
                ('status', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=32)),
                ('last_tick', models.DateTimeField(null=True)),
                ('next_tick', models.IntegerField()),
                ('gamestate', models.JSONField(default=dict)),
                ('options', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('chat_log', models.JSONField(default=list)),
            ],
        ),
    ]
