# Generated by Django 4.0.4 on 2022-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='next_tick',
            field=models.IntegerField(null=True),
        ),
    ]
